source 'https://rubygems.org'

# Install omnibus
gem 'omnibus', '~> 7.0', '>= 7.0.12'

# Use Chef's software definitions. It is recommended that you write your own
# software definitions, but you can clone/fork Chef's to get you started.
gem 'omnibus-software', github: 'opscode/omnibus-software'

# This development group is installed by default when you run `bundle install`,
# but if you are using Omnibus in a CI-based infrastructure, you do not need
# the Test Kitchen-based build lab. You can skip these unnecessary dependencies
# by running `bundle install --without development` to speed up build times.
group :development do
  # Use Berkshelf for resolving cookbook dependencies
  gem 'berkshelf', '~> 7.0.2'

  # Use Test Kitchen with Vagrant for converging the build environment
  gem 'test-kitchen', '~> 2.5', '>= 2.5.2'
  gem 'kitchen-vagrant', '~> 1.5', '>= 1.5.1'
  gem 'kitchen-ec2', '~> 2.5.0'
  gem 'winrm-transport', '~> 1.0.3'
  gem 'serverspec',      '~> 2.29.0'
end
